# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testing routes and supported node version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Installing deps
    - name: Installing Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    # npm clean install https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci
    - name: Installing dependencies
      run: npm ci
    - name: Building 'Api Colors'
      run: npm run build
    # path is in 'build' folder
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build

  # Build:
  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    # Installing deps
    - name: Installing Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # Install Test deps
    - name: Install Playwright
      run: npx playwright install --with-deps
      
    # Download previous build
    - uses: actions/download-artifact@v4
      with:
        name: build
        path: build
    
    - name: Start server
      run: npm run start &
    - name: Wait for server to start
      run: sleep 6
      
    - name: Running Test
      run: npm run test
    # Upload test result as artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
